# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is only read once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: /1819-nmd3-project-docenten # the subpath of your site, e.g. /blog
# host : 127.0.0.1
# port : 4000

# Custom Site variables
# ─────────────────────
title: New Media Design 3 2018-2019

# Build settings
# ──────────────
defaults:

exclude:
  - Gemfile

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
  - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed